import * as React from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faNewspaper, faRocket } from '@fortawesome/free-solid-svg-icons'
import { faYoutube } from '@fortawesome/free-brands-svg-icons'

export default function Home({ launches }) {

  const [clicked, setClicked] = React.useState(false);
  const [darkMode, setDarkMode] = React.useState(true);

  const handleClick = () => {
    setClicked(!clicked);
  };
  const handleDarkMode = () => {
    setDarkMode(!darkMode);
  };
  
  const mappedLaunches = launches.map(launch => {
    return (
        <div key={launch.id}  className={styles.card}>

            <h2>{launch.mission_name}</h2><img className={styles.patch} src={launch.links.mission_patch_small}></img>
              <p className={styles.left}><strong>Launch Date: </strong>{new Date(launch.launch_date_local).toLocaleDateString("en-ca")}</p>
              <p className={styles.left}>{launch.rocket.rocket_name} <FontAwesomeIcon icon={faRocket}/></p>
            
            <sub>{launch.launch_site.site_name_long}</sub>

              {launch.details && <div className={clicked ? styles.detailsmore : styles.details}>{launch.details}</div>}

              <div className={styles.linkdiv}>
                  {launch.links.video_link && <a className={styles.links} href={launch.links.video_link} target="_blank"><FontAwesomeIcon icon={faYoutube}/></a>}
                  {launch.links.article_link && <a className={styles.links} href={launch.links.article_link} target="_blank"><FontAwesomeIcon icon={faNewspaper}/></a>}
                  
              </div>           
        </div>
      
    )
  });

  return (
    <div className={darkMode? styles.container : styles.containerdark}>
        <Head>
          <title>SpaceX Launch Tracker</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <main className={styles.main}>
        {darkMode ? <button className={styles.lightswitch} onClick={handleDarkMode}>🌙<sup></sup></button> : <button className={styles.lightswitch} onClick={handleDarkMode}>☀️</button>}
            <h1 className={styles.title}>
            SpaceX Launch Tracker
            </h1>

            <p className={styles.description}>
              Latest SpaceX Launches<br></br>
            </p>

            {clicked ? <button className={styles.expand} onClick={handleClick}>Shrink All</button> : <button className={styles.expand} onClick={handleClick}>Expand All</button>}
            

            <div className={styles.grid}>
              {mappedLaunches}
            </div>

        </main>
    </div>
  )
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'https://api.spacex.land/graphql/',
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      query GetLaunches {
        launchesPast(limit: 25) {
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
            flickr_images
            mission_patch_small
          }
          id
          rocket {
            rocket_name
          }
          details
        }
      }
      
    `
  })

  return {
    props: {
      launches: data.launchesPast
    }
  }
}